version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"  # Porta principal da LocalStack
      - "4510-4559:4510-4559"  # Portas adicionais usadas pelo DynamoDB
    environment:
      - LOCALSTACK_API_KEY=your_api_key
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "/var/lib/localstack"
